### ISSUE TITLE
Squashfs Image Support for Centos 7

### ISSUE THREAD

**Issue by rtznprmpftl** [RexOps/repositorio#20]
Since Centos 7 there is a Sqashfs image under /os/x86_64/LiveOS/ . It would be nice if repositor.io would include it in mirrored repos, since the default foreman pxe installation depends on this.

**Comment by krimdomu** [comment]
Hi @rtznprmpftl,
thanks for the report. This is now fixed and will be included in the next release. 
You can also download the patched file directly and replace the one from your installation:
https://raw.githubusercontent.com/RexOps/repositorio/c1a7aef04f3a8f25f3f6ced6c61275d3bddda3ae/lib/Rex/Repositorio/Repository/Yum.pm
