### ISSUE TITLE
Problem with ubuntu Images

### ISSUE THREAD

**Issue by rtznprmpftl** [RexOps/repositorio#23]
I think repositor.io has problems Downloading the Ubuntu pxe images.
This could be because the Ubuntu Location differs from the Debian Location:
http://de.archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/
vs. 
http://ftp.de.debian.org/debian/dists/jessie/main/installer-amd64/current/images/netboot/debian-installer/amd64/

Config:

    <Repository ubuntu-trusty-amd64-main>
      url       = http://de.archive.ubuntu.com/ubuntu/
      local     = ubuntu-trusty-amd64-main/ubuntu/
      type      = Apt
      arch      = amd64
      dist      = trusty
      component = main
      images    = true
    </Repository>

Output:

    [root@repo trusty]# repositorio --mirror --repo=ubuntu-trusty-amd64-main
    >> Going to mirror ubuntu-trusty-amd64-main. This may take a while. 
    
    >> Downloading metadata... 

    100%     [==============================================================================================================================================================]
    
    >> Downloading file listing... 
    
    100%     [==============================================================================================================================================================]
    
    >> Downloading packages for main (amd64)... 
    dists/jessie/main/installer-amd64/current/images/netboot/
    100%     [==============================================================================================================================================================]
    
    >> Downloading installer packages for main (amd64)... 
    
    100%     [==============================================================================================================================================================]    No such file or directory at /usr/local/share/perl5/Rex/Repositorio/Repository/Apt.pm line 363.
    [root@repo trusty]#

**Comment by krimdomu** [comment]
Hi @rtznprmpftl ,

this seems to be a bug in the ubuntu repositories. They don't list all files in the *Release* file of the repository (Debian repositories list all files inside the *Release* file)

But i think that ubuntu won't change their repositories, so repositorio have to deal with this.

**Comment by krimdomu** [comment]
Hi @rtznprmpftl 
could you please try this patch?
You can download the complete file here: https://raw.githubusercontent.com/RexOps/repositorio/8b831720fe7527afce19ad2c00dcf067b402e374/lib/Rex/Repositorio/Repository/Apt.pm

**Comment by rtznprmpftl** [comment]
Looks good

**Comment by krimdomu** [comment]
@rtznprmpftl thanks so i'm going to close this ticket
