### ISSUE TITLE
Add option to also download udeb files 

### ISSUE THREAD

**Issue by rtznprmpftl** [RexOps/repositorio#24]
The ubuntu Repository
    
    <Repository ubuntu-trusty-amd64-main-updates>
      url       = http://de.archive.ubuntu.com/ubuntu/
      local     = ubuntu/
      type      = Apt
      arch      = amd64
      dist      = trusty-updates
      component = main
    </Repository>

includes some udeb files which are needed for baremetal provisioning:
for example here:
http://ubuntu-master.mirror.tudos.de/ubuntu/pool/main/l/linux-lts-utopic/

which repositor.io doesnt download.

information about udeb:
https://d-i.alioth.debian.org/doc/internals/ch03.html

**Comment by rtznprmpftl** [comment]
Ahh i just saw that they get downloaded when i add the `images = true` option

**Comment by krimdomu** [comment]
Hi @rtznprmpftl ,

yes these packages should be downloaded when the `images=true` option is set because they are belonging to the installer.
