### ISSUE TITLE
Add "resume on failure" option

### ISSUE THREAD

**Issue by rtznprmpftl** [RexOps/repositorio#26]
Right now, when mirroring a repository and a 404 or different error occurs, the mirroring stops.
This is a little bit annoying when you have not much bandwidth and are mirroring over night.

So an option that tells repositorio to continue mirroring, even when a package is not available would be nice.

**Comment by krimdomu** [comment]
Hi @rtznprmpftl 
in the upcoming 1.2 release will be an option DownloadSkip404 which can be set to "true". This will skip package files that are not found on server side.
