### ISSUE TITLE
Suse/YaST support

### ISSUE THREAD

**Issue by DavidIAm** [RexOps/repositorio#8]
I see you have a module in there for mirroring opensuse/yast type repositories, but your documentation says that YaST is not supported (or doesn't say that it is, at least).

As I am somewhat cornered into using OpenSUSE on a set of servers I want to manage using Rex, and I'll be distributing some custom packages from my own custom repositories, I think helping augment repositorio to enable this support would be the shortest development distance between these points. (I could use YUM support in zypper, I suppose, but... that doesn't seem optimal?)

Please communicate and coordinate with me your feelings on the value of this feature and possible contributions to that goal.

David

**Comment by krimdomu** [comment]
Hi David,

the YaST Type repositories are currently in development for the next version :-)

The master branch is the development branch. I think the mirroring of an OpenSuSE repository should work (at least it downloads things, i haven't had the time to test the mirrored repository with a OpenSuSE system yet).

The goal is to release the next version of repositorio in about 2 or 3 weeks.

**Comment by DavidIAm** [comment]
Halleljuah. I shall remain tuned and ears pricked.

**Comment by krimdomu** [comment]
It took a bit longer, but in the next release 0.7.0 there will be support for mirroring OpenSuSE repositories.

If you create custom repositories, repositorio will create yum style repos for OpenSuSE. Zypper/Yast can handle this style of repositores, so this is no problem and i also don't see any disadvantages (the only one is, that with yum style repos it is not possible to create multi-volume repos, but this counts only for repositories that should be burned on a dvd or cd)

They can be added with the following command:
```
zypper ar -t YUM http://location/ alias
```
